// Package rust provides the Rust language plugin for versionator.
//
// Rust projects use Cargo for versioning. This plugin configures
// versionator with Rust-specific defaults:
//   - No version prefix (Cargo uses bare version numbers)
//   - Output path: src/version.rs
//   - Pre-release format using dots (e.g., alpha.1) per Cargo conventions
//
// The generated version file contains constants:
//
//	// Auto-generated by versionator. Do not edit.
//	pub const VERSION: &str = "1.2.3";
//	pub const MAJOR: u32 = 1;
//	pub const MINOR: u32 = 2;
//	pub const PATCH: u32 = 3;
//	pub const GIT_HASH: &str = "abc1234";
//
// Include this module in your lib.rs or main.rs:
//
//	mod version;
//	use version::VERSION;
package rust

import (
	"github.com/benjaminabbitt/versionator/internal/plugin"
)

// Plugin implements the LanguagePlugin interface for Rust
type Plugin struct{}

// Name returns the plugin name
func (p *Plugin) Name() string {
	return "rust"
}

// Types returns the plugin types this plugin implements
func (p *Plugin) Types() plugin.PluginTypeSet {
	return plugin.NewPluginTypeSet(plugin.TypeLanguage)
}

// LanguageName returns the language identifier
func (p *Plugin) LanguageName() string {
	return "rust"
}

// GetEmitConfig returns configuration for Rust source file emission
func (p *Plugin) GetEmitConfig() *plugin.EmitConfig {
	return &plugin.EmitConfig{
		DefaultOutputPath:  "src/version.rs",
		DefaultPackageName: "",
		FileExtension:      ".rs",
	}
}

// GetBuildConfig returns configuration for Rust build-time injection via env vars
// Use with: $(versionator emit build rust) cargo build
// In Rust code: const VERSION: &str = env!("VERSION");
func (p *Plugin) GetBuildConfig() *plugin.LinkConfig {
	return &plugin.LinkConfig{
		VariablePath: "VERSION",
		FlagTemplate: "{{Variable}}={{Value}}",
	}
}

// GetPatchConfigs returns configuration for patching Cargo.toml
func (p *Plugin) GetPatchConfigs() []plugin.PatchConfig {
	return []plugin.PatchConfig{
		{
			Name:        "Cargo.toml",
			FilePath:    "Cargo.toml",
			Format:      plugin.PatchFormatTOML,
			VersionPath: "package.version",
			Description: "Cargo package manifest",
			Patch:       plugin.PatchTOML(),
		},
	}
}

func init() {
	plugin.Register(&Plugin{})
}
