// Package javascript provides the JavaScript language plugin for versionator.
//
// JavaScript/Node.js projects typically use npm's semantic versioning.
// This plugin configures versionator with JavaScript-specific defaults:
//   - No version prefix
//   - Output path: version.js
//
// The generated version file exports version constants:
//
//	// Auto-generated by versionator. Do not edit.
//	module.exports = {
//	    VERSION: "1.2.3",
//	    MAJOR: 1,
//	    MINOR: 2,
//	    PATCH: 3,
//	    GIT_HASH: "abc1234"
//	};
//
// For ES modules, consider using the TypeScript plugin with .mjs extension.
package javascript

import (
	"github.com/benjaminabbitt/versionator/pkg/plugin"
)

// Plugin implements the LanguagePlugin interface for JavaScript
type Plugin struct{}

// Name returns the plugin name
func (p *Plugin) Name() string {
	return "javascript"
}

// Types returns the plugin types this plugin implements
func (p *Plugin) Types() plugin.PluginTypeSet {
	return plugin.NewPluginTypeSet(plugin.TypeLanguage)
}

// LanguageName returns the language identifier
func (p *Plugin) LanguageName() string {
	return "javascript"
}

// GetEmitConfig returns configuration for JavaScript source file emission
func (p *Plugin) GetEmitConfig() *plugin.EmitConfig {
	return &plugin.EmitConfig{
		DefaultOutputPath:  "version.js",
		DefaultPackageName: "",
		FileExtension:      ".js",
	}
}

// GetBuildConfig returns nil - JavaScript doesn't support link-time injection
func (p *Plugin) GetBuildConfig() *plugin.LinkConfig {
	return nil
}

// GetPatchConfigs returns configuration for patching package.json
func (p *Plugin) GetPatchConfigs() []plugin.PatchConfig {
	return []plugin.PatchConfig{
		{
			Name:        "package.json",
			FilePath:    "package.json",
			Format:      plugin.PatchFormatJSON,
			VersionPath: "version",
			Description: "npm/Node.js package manifest",
			Patch:       plugin.PatchJSON(),
		},
	}
}

func init() {
	plugin.Register(&Plugin{})
}
