// Package typescript provides the TypeScript language plugin for versionator.
//
// TypeScript projects benefit from typed version exports. This plugin
// configures versionator with TypeScript-specific defaults:
//   - No version prefix
//   - Output path: version.ts
//
// The generated version file exports typed constants:
//
//	// Auto-generated by versionator. Do not edit.
//	export const VERSION: string = "1.2.3";
//	export const MAJOR: number = 1;
//	export const MINOR: number = 2;
//	export const PATCH: number = 3;
//	export const GIT_HASH: string = "abc1234";
package typescript

import (
	"github.com/benjaminabbitt/versionator/pkg/plugin"
)

// Plugin implements the LanguagePlugin interface for TypeScript
type Plugin struct{}

// Name returns the plugin name
func (p *Plugin) Name() string {
	return "typescript"
}

// Types returns the plugin types this plugin implements
func (p *Plugin) Types() plugin.PluginTypeSet {
	return plugin.NewPluginTypeSet(plugin.TypeLanguage)
}

// LanguageName returns the language identifier
func (p *Plugin) LanguageName() string {
	return "typescript"
}

// GetEmitConfig returns configuration for TypeScript source file emission
func (p *Plugin) GetEmitConfig() *plugin.EmitConfig {
	return &plugin.EmitConfig{
		DefaultOutputPath:  "version.ts",
		DefaultPackageName: "",
		FileExtension:      ".ts",
	}
}

// GetBuildConfig returns nil - TypeScript doesn't support link-time injection
func (p *Plugin) GetBuildConfig() *plugin.LinkConfig {
	return nil
}

// GetPatchConfigs returns configuration for patching package.json
func (p *Plugin) GetPatchConfigs() []plugin.PatchConfig {
	return []plugin.PatchConfig{
		{
			Name:        "package.json",
			FilePath:    "package.json",
			Format:      plugin.PatchFormatJSON,
			VersionPath: "version",
			Description: "npm/Node.js package manifest",
			Patch:       plugin.PatchJSON(),
		},
	}
}

func init() {
	plugin.Register(&Plugin{})
}
