// Code generated by MockGen. DO NOT EDIT.
// Source: versionator/internal/vcs (interfaces: VersionControlSystem)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	"time"

	gomock "github.com/golang/mock/gomock"
)

// MockVersionControlSystem is a mock of VersionControlSystem interface.
type MockVersionControlSystem struct {
	ctrl     *gomock.Controller
	recorder *MockVersionControlSystemMockRecorder
}

// MockVersionControlSystemMockRecorder is the mock recorder for MockVersionControlSystem.
type MockVersionControlSystemMockRecorder struct {
	mock *MockVersionControlSystem
}

// NewMockVersionControlSystem creates a new mock instance.
func NewMockVersionControlSystem(ctrl *gomock.Controller) *MockVersionControlSystem {
	mock := &MockVersionControlSystem{ctrl: ctrl}
	mock.recorder = &MockVersionControlSystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionControlSystem) EXPECT() *MockVersionControlSystemMockRecorder {
	return m.recorder
}

// CreateTag mock base method.
func (m *MockVersionControlSystem) CreateTag(tagName, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTag", tagName, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTag indicates an expected call of CreateTag.
func (mr *MockVersionControlSystemMockRecorder) CreateTag(tagName, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTag", reflect.TypeOf((*MockVersionControlSystem)(nil).CreateTag), tagName, message)
}

// GetRepositoryRoot mock base method.
func (m *MockVersionControlSystem) GetRepositoryRoot() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryRoot")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryRoot indicates an expected call of GetRepositoryRoot.
func (mr *MockVersionControlSystemMockRecorder) GetRepositoryRoot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryRoot", reflect.TypeOf((*MockVersionControlSystem)(nil).GetRepositoryRoot))
}

// GetVCSIdentifier mock base method.
func (m *MockVersionControlSystem) GetVCSIdentifier(length int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVCSIdentifier", length)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVCSIdentifier indicates an expected call of GetVCSIdentifier.
func (mr *MockVersionControlSystemMockRecorder) GetVCSIdentifier(length interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVCSIdentifier", reflect.TypeOf((*MockVersionControlSystem)(nil).GetVCSIdentifier), length)
}

// IsRepository mock base method.
func (m *MockVersionControlSystem) IsRepository() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRepository")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRepository indicates an expected call of IsRepository.
func (mr *MockVersionControlSystemMockRecorder) IsRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRepository", reflect.TypeOf((*MockVersionControlSystem)(nil).IsRepository))
}

// IsWorkingDirectoryClean mock base method.
func (m *MockVersionControlSystem) IsWorkingDirectoryClean() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsWorkingDirectoryClean")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsWorkingDirectoryClean indicates an expected call of IsWorkingDirectoryClean.
func (mr *MockVersionControlSystemMockRecorder) IsWorkingDirectoryClean() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsWorkingDirectoryClean", reflect.TypeOf((*MockVersionControlSystem)(nil).IsWorkingDirectoryClean))
}

// Name mock base method.
func (m *MockVersionControlSystem) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockVersionControlSystemMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockVersionControlSystem)(nil).Name))
}

// TagExists mock base method.
func (m *MockVersionControlSystem) TagExists(tagName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagExists", tagName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagExists indicates an expected call of TagExists.
func (mr *MockVersionControlSystemMockRecorder) TagExists(tagName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagExists", reflect.TypeOf((*MockVersionControlSystem)(nil).TagExists), tagName)
}

// GetBranchName mock base method.
func (m *MockVersionControlSystem) GetBranchName() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBranchName")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBranchName indicates an expected call of GetBranchName.
func (mr *MockVersionControlSystemMockRecorder) GetBranchName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBranchName", reflect.TypeOf((*MockVersionControlSystem)(nil).GetBranchName))
}

// GetCommitDate mock base method.
func (m *MockVersionControlSystem) GetCommitDate() (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitDate")
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitDate indicates an expected call of GetCommitDate.
func (mr *MockVersionControlSystemMockRecorder) GetCommitDate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitDate", reflect.TypeOf((*MockVersionControlSystem)(nil).GetCommitDate))
}

// GetCommitsSinceTag mock base method.
func (m *MockVersionControlSystem) GetCommitsSinceTag() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitsSinceTag")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitsSinceTag indicates an expected call of GetCommitsSinceTag.
func (mr *MockVersionControlSystemMockRecorder) GetCommitsSinceTag() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitsSinceTag", reflect.TypeOf((*MockVersionControlSystem)(nil).GetCommitsSinceTag))
}

// GetUncommittedChanges mock base method.
func (m *MockVersionControlSystem) GetUncommittedChanges() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUncommittedChanges")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUncommittedChanges indicates an expected call of GetUncommittedChanges.
func (mr *MockVersionControlSystemMockRecorder) GetUncommittedChanges() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUncommittedChanges", reflect.TypeOf((*MockVersionControlSystem)(nil).GetUncommittedChanges))
}

// GetLastTag mock base method.
func (m *MockVersionControlSystem) GetLastTag() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastTag")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastTag indicates an expected call of GetLastTag.
func (mr *MockVersionControlSystemMockRecorder) GetLastTag() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastTag", reflect.TypeOf((*MockVersionControlSystem)(nil).GetLastTag))
}

// GetLastTagCommit mock base method.
func (m *MockVersionControlSystem) GetLastTagCommit() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastTagCommit")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastTagCommit indicates an expected call of GetLastTagCommit.
func (mr *MockVersionControlSystemMockRecorder) GetLastTagCommit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastTagCommit", reflect.TypeOf((*MockVersionControlSystem)(nil).GetLastTagCommit))
}

// GetCommitAuthor mock base method.
func (m *MockVersionControlSystem) GetCommitAuthor() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitAuthor")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitAuthor indicates an expected call of GetCommitAuthor.
func (mr *MockVersionControlSystemMockRecorder) GetCommitAuthor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitAuthor", reflect.TypeOf((*MockVersionControlSystem)(nil).GetCommitAuthor))
}

// GetCommitAuthorEmail mock base method.
func (m *MockVersionControlSystem) GetCommitAuthorEmail() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitAuthorEmail")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitAuthorEmail indicates an expected call of GetCommitAuthorEmail.
func (mr *MockVersionControlSystemMockRecorder) GetCommitAuthorEmail() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitAuthorEmail", reflect.TypeOf((*MockVersionControlSystem)(nil).GetCommitAuthorEmail))
}

