// Package ruby provides the Ruby language plugin for versionator.
//
// Ruby gems use a .gemspec file for gem specification including version:
//
//	Gem::Specification.new do |spec|
//	  spec.name    = "mygem"
//	  spec.version = "1.2.3"
//	end
//
// The generated version.rb file contains:
//
//	# frozen_string_literal: true
//	# Auto-generated by versionator. Do not edit.
//
//	module Version
//	  VERSION = "1.2.3"
//	  MAJOR = 1
//	  MINOR = 2
//	  PATCH = 3
//	end
//
// Injection methods:
//   - emit: Generate version.rb with constants
//   - patch: Update version in .gemspec (requires custom handling)
package ruby

import (
	"github.com/benjaminabbitt/versionator/internal/plugin"
)

// Plugin implements the LanguagePlugin interface for Ruby
type Plugin struct{}

// Name returns the plugin name
func (p *Plugin) Name() string {
	return "ruby"
}

// Types returns the plugin types this plugin implements
func (p *Plugin) Types() plugin.PluginTypeSet {
	return plugin.NewPluginTypeSet(plugin.TypeLanguage)
}

// LanguageName returns the language identifier
func (p *Plugin) LanguageName() string {
	return "ruby"
}

// GetEmitConfig returns configuration for Ruby source file emission
func (p *Plugin) GetEmitConfig() *plugin.EmitConfig {
	return &plugin.EmitConfig{
		DefaultOutputPath:  "lib/version.rb",
		DefaultPackageName: "",
		FileExtension:      ".rb",
	}
}

// GetBuildConfig returns nil - Ruby doesn't support link-time injection
func (p *Plugin) GetBuildConfig() *plugin.LinkConfig {
	return nil
}

// GetPatchConfigs returns configuration for patching Ruby gemspec files
func (p *Plugin) GetPatchConfigs() []plugin.PatchConfig {
	return []plugin.PatchConfig{
		{
			Name:        "gemspec",
			FilePath:    "*.gemspec",
			Format:      plugin.PatchFormatRuby,
			VersionPath: "spec.version",
			Description: "Ruby gem specification",
			Patch:       plugin.PatchRubyGemspec(),
		},
	}
}

func init() {
	plugin.Register(&Plugin{})
}
