// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: pkg/plugin/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{0}
}

// Emit plugin messages
type EmitInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                        // Plugin name (e.g., "go-emit")
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`                                    // Format identifier (e.g., "go", "python")
	FileExtension string                 `protobuf:"bytes,3,opt,name=file_extension,json=fileExtension,proto3" json:"file_extension,omitempty"` // File extension (e.g., ".go", ".py")
	DefaultOutput string                 `protobuf:"bytes,4,opt,name=default_output,json=defaultOutput,proto3" json:"default_output,omitempty"` // Default output path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitInfo) Reset() {
	*x = EmitInfo{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitInfo) ProtoMessage() {}

func (x *EmitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitInfo.ProtoReflect.Descriptor instead.
func (*EmitInfo) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *EmitInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmitInfo) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *EmitInfo) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

func (x *EmitInfo) GetDefaultOutput() string {
	if x != nil {
		return x.DefaultOutput
	}
	return ""
}

type EmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vars          map[string]string      `protobuf:"bytes,1,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Template variables (Version, Major, Minor, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitRequest) Reset() {
	*x = EmitRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitRequest) ProtoMessage() {}

func (x *EmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitRequest.ProtoReflect.Descriptor instead.
func (*EmitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *EmitRequest) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

type EmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitResponse) Reset() {
	*x = EmitResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitResponse) ProtoMessage() {}

func (x *EmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitResponse.ProtoReflect.Descriptor instead.
func (*EmitResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *EmitResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EmitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Build plugin messages
type BuildInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // Plugin name (e.g., "go-build")
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"` // Format identifier (e.g., "go", "rust")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildInfo) Reset() {
	*x = BuildInfo{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildInfo) ProtoMessage() {}

func (x *BuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildInfo.ProtoReflect.Descriptor instead.
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *BuildInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuildInfo) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type BuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vars          map[string]string      `protobuf:"bytes,1,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Template variables
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *BuildRequest) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

type BuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         string                 `protobuf:"bytes,1,opt,name=flags,proto3" json:"flags,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *BuildResponse) GetFlags() string {
	if x != nil {
		return x.Flags
	}
	return ""
}

func (x *BuildResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Patch plugin messages
type PatchInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // Plugin name (e.g., "patch-maven")
	FilePattern   string                 `protobuf:"bytes,2,opt,name=file_pattern,json=filePattern,proto3" json:"file_pattern,omitempty"` // File to patch (e.g., "pom.xml", "package.json")
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                    // Human-readable description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchInfo) Reset() {
	*x = PatchInfo{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchInfo) ProtoMessage() {}

func (x *PatchInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchInfo.ProtoReflect.Descriptor instead.
func (*PatchInfo) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *PatchInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PatchInfo) GetFilePattern() string {
	if x != nil {
		return x.FilePattern
	}
	return ""
}

func (x *PatchInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"` // File content to patch
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // New version string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchRequest) Reset() {
	*x = PatchRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchRequest) ProtoMessage() {}

func (x *PatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchRequest.ProtoReflect.Descriptor instead.
func (*PatchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *PatchRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PatchRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"` // Patched content
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchResponse) Reset() {
	*x = PatchResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchResponse) ProtoMessage() {}

func (x *PatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchResponse.ProtoReflect.Descriptor instead.
func (*PatchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *PatchResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_plugin_proto_plugin_proto protoreflect.FileDescriptor

const file_pkg_plugin_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/plugin/proto/plugin.proto\x12\x05proto\"\a\n" +
	"\x05Empty\"\x84\x01\n" +
	"\bEmitInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12%\n" +
	"\x0efile_extension\x18\x03 \x01(\tR\rfileExtension\x12%\n" +
	"\x0edefault_output\x18\x04 \x01(\tR\rdefaultOutput\"x\n" +
	"\vEmitRequest\x120\n" +
	"\x04vars\x18\x01 \x03(\v2\x1c.proto.EmitRequest.VarsEntryR\x04vars\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\fEmitResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"7\n" +
	"\tBuildInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"z\n" +
	"\fBuildRequest\x121\n" +
	"\x04vars\x18\x01 \x03(\v2\x1d.proto.BuildRequest.VarsEntryR\x04vars\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\rBuildResponse\x12\x14\n" +
	"\x05flags\x18\x01 \x01(\tR\x05flags\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"d\n" +
	"\tPatchInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\ffile_pattern\x18\x02 \x01(\tR\vfilePattern\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"B\n" +
	"\fPatchRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"?\n" +
	"\rPatchResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2g\n" +
	"\n" +
	"EmitPlugin\x12(\n" +
	"\aGetInfo\x12\f.proto.Empty\x1a\x0f.proto.EmitInfo\x12/\n" +
	"\x04Emit\x12\x12.proto.EmitRequest\x1a\x13.proto.EmitResponse2t\n" +
	"\vBuildPlugin\x12)\n" +
	"\aGetInfo\x12\f.proto.Empty\x1a\x10.proto.BuildInfo\x12:\n" +
	"\rGenerateFlags\x12\x13.proto.BuildRequest\x1a\x14.proto.BuildResponse2l\n" +
	"\vPatchPlugin\x12)\n" +
	"\aGetInfo\x12\f.proto.Empty\x1a\x10.proto.PatchInfo\x122\n" +
	"\x05Patch\x12\x13.proto.PatchRequest\x1a\x14.proto.PatchResponseB8Z6github.com/benjaminabbitt/versionator/pkg/plugin/protob\x06proto3"

var (
	file_pkg_plugin_proto_plugin_proto_rawDescOnce sync.Once
	file_pkg_plugin_proto_plugin_proto_rawDescData []byte
)

func file_pkg_plugin_proto_plugin_proto_rawDescGZIP() []byte {
	file_pkg_plugin_proto_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_plugin_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_plugin_proto_rawDesc), len(file_pkg_plugin_proto_plugin_proto_rawDesc)))
	})
	return file_pkg_plugin_proto_plugin_proto_rawDescData
}

var file_pkg_plugin_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_plugin_proto_plugin_proto_goTypes = []any{
	(*Empty)(nil),         // 0: proto.Empty
	(*EmitInfo)(nil),      // 1: proto.EmitInfo
	(*EmitRequest)(nil),   // 2: proto.EmitRequest
	(*EmitResponse)(nil),  // 3: proto.EmitResponse
	(*BuildInfo)(nil),     // 4: proto.BuildInfo
	(*BuildRequest)(nil),  // 5: proto.BuildRequest
	(*BuildResponse)(nil), // 6: proto.BuildResponse
	(*PatchInfo)(nil),     // 7: proto.PatchInfo
	(*PatchRequest)(nil),  // 8: proto.PatchRequest
	(*PatchResponse)(nil), // 9: proto.PatchResponse
	nil,                   // 10: proto.EmitRequest.VarsEntry
	nil,                   // 11: proto.BuildRequest.VarsEntry
}
var file_pkg_plugin_proto_plugin_proto_depIdxs = []int32{
	10, // 0: proto.EmitRequest.vars:type_name -> proto.EmitRequest.VarsEntry
	11, // 1: proto.BuildRequest.vars:type_name -> proto.BuildRequest.VarsEntry
	0,  // 2: proto.EmitPlugin.GetInfo:input_type -> proto.Empty
	2,  // 3: proto.EmitPlugin.Emit:input_type -> proto.EmitRequest
	0,  // 4: proto.BuildPlugin.GetInfo:input_type -> proto.Empty
	5,  // 5: proto.BuildPlugin.GenerateFlags:input_type -> proto.BuildRequest
	0,  // 6: proto.PatchPlugin.GetInfo:input_type -> proto.Empty
	8,  // 7: proto.PatchPlugin.Patch:input_type -> proto.PatchRequest
	1,  // 8: proto.EmitPlugin.GetInfo:output_type -> proto.EmitInfo
	3,  // 9: proto.EmitPlugin.Emit:output_type -> proto.EmitResponse
	4,  // 10: proto.BuildPlugin.GetInfo:output_type -> proto.BuildInfo
	6,  // 11: proto.BuildPlugin.GenerateFlags:output_type -> proto.BuildResponse
	7,  // 12: proto.PatchPlugin.GetInfo:output_type -> proto.PatchInfo
	9,  // 13: proto.PatchPlugin.Patch:output_type -> proto.PatchResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_plugin_proto_plugin_proto_init() }
func file_pkg_plugin_proto_plugin_proto_init() {
	if File_pkg_plugin_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_plugin_proto_rawDesc), len(file_pkg_plugin_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_pkg_plugin_proto_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_plugin_proto_plugin_proto_depIdxs,
		MessageInfos:      file_pkg_plugin_proto_plugin_proto_msgTypes,
	}.Build()
	File_pkg_plugin_proto_plugin_proto = out.File
	file_pkg_plugin_proto_plugin_proto_goTypes = nil
	file_pkg_plugin_proto_plugin_proto_depIdxs = nil
}
