// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: pkg/plugin/proto/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmitPlugin_GetInfo_FullMethodName = "/proto.EmitPlugin/GetInfo"
	EmitPlugin_Emit_FullMethodName    = "/proto.EmitPlugin/Emit"
)

// EmitPluginClient is the client API for EmitPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EmitPlugin service - generates version source files
type EmitPluginClient interface {
	GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EmitInfo, error)
	Emit(ctx context.Context, in *EmitRequest, opts ...grpc.CallOption) (*EmitResponse, error)
}

type emitPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewEmitPluginClient(cc grpc.ClientConnInterface) EmitPluginClient {
	return &emitPluginClient{cc}
}

func (c *emitPluginClient) GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EmitInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitInfo)
	err := c.cc.Invoke(ctx, EmitPlugin_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emitPluginClient) Emit(ctx context.Context, in *EmitRequest, opts ...grpc.CallOption) (*EmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitResponse)
	err := c.cc.Invoke(ctx, EmitPlugin_Emit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmitPluginServer is the server API for EmitPlugin service.
// All implementations must embed UnimplementedEmitPluginServer
// for forward compatibility.
//
// EmitPlugin service - generates version source files
type EmitPluginServer interface {
	GetInfo(context.Context, *Empty) (*EmitInfo, error)
	Emit(context.Context, *EmitRequest) (*EmitResponse, error)
	mustEmbedUnimplementedEmitPluginServer()
}

// UnimplementedEmitPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmitPluginServer struct{}

func (UnimplementedEmitPluginServer) GetInfo(context.Context, *Empty) (*EmitInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedEmitPluginServer) Emit(context.Context, *EmitRequest) (*EmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Emit not implemented")
}
func (UnimplementedEmitPluginServer) mustEmbedUnimplementedEmitPluginServer() {}
func (UnimplementedEmitPluginServer) testEmbeddedByValue()                    {}

// UnsafeEmitPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmitPluginServer will
// result in compilation errors.
type UnsafeEmitPluginServer interface {
	mustEmbedUnimplementedEmitPluginServer()
}

func RegisterEmitPluginServer(s grpc.ServiceRegistrar, srv EmitPluginServer) {
	// If the following call panics, it indicates UnimplementedEmitPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmitPlugin_ServiceDesc, srv)
}

func _EmitPlugin_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmitPluginServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmitPlugin_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmitPluginServer).GetInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmitPlugin_Emit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmitPluginServer).Emit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmitPlugin_Emit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmitPluginServer).Emit(ctx, req.(*EmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmitPlugin_ServiceDesc is the grpc.ServiceDesc for EmitPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmitPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EmitPlugin",
	HandlerType: (*EmitPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _EmitPlugin_GetInfo_Handler,
		},
		{
			MethodName: "Emit",
			Handler:    _EmitPlugin_Emit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugin/proto/plugin.proto",
}

const (
	BuildPlugin_GetInfo_FullMethodName       = "/proto.BuildPlugin/GetInfo"
	BuildPlugin_GenerateFlags_FullMethodName = "/proto.BuildPlugin/GenerateFlags"
)

// BuildPluginClient is the client API for BuildPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BuildPlugin service - generates build/linker flags
type BuildPluginClient interface {
	GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BuildInfo, error)
	GenerateFlags(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error)
}

type buildPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewBuildPluginClient(cc grpc.ClientConnInterface) BuildPluginClient {
	return &buildPluginClient{cc}
}

func (c *buildPluginClient) GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BuildInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildInfo)
	err := c.cc.Invoke(ctx, BuildPlugin_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildPluginClient) GenerateFlags(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildResponse)
	err := c.cc.Invoke(ctx, BuildPlugin_GenerateFlags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildPluginServer is the server API for BuildPlugin service.
// All implementations must embed UnimplementedBuildPluginServer
// for forward compatibility.
//
// BuildPlugin service - generates build/linker flags
type BuildPluginServer interface {
	GetInfo(context.Context, *Empty) (*BuildInfo, error)
	GenerateFlags(context.Context, *BuildRequest) (*BuildResponse, error)
	mustEmbedUnimplementedBuildPluginServer()
}

// UnimplementedBuildPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuildPluginServer struct{}

func (UnimplementedBuildPluginServer) GetInfo(context.Context, *Empty) (*BuildInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedBuildPluginServer) GenerateFlags(context.Context, *BuildRequest) (*BuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateFlags not implemented")
}
func (UnimplementedBuildPluginServer) mustEmbedUnimplementedBuildPluginServer() {}
func (UnimplementedBuildPluginServer) testEmbeddedByValue()                     {}

// UnsafeBuildPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuildPluginServer will
// result in compilation errors.
type UnsafeBuildPluginServer interface {
	mustEmbedUnimplementedBuildPluginServer()
}

func RegisterBuildPluginServer(s grpc.ServiceRegistrar, srv BuildPluginServer) {
	// If the following call panics, it indicates UnimplementedBuildPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuildPlugin_ServiceDesc, srv)
}

func _BuildPlugin_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildPluginServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildPlugin_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildPluginServer).GetInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildPlugin_GenerateFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildPluginServer).GenerateFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildPlugin_GenerateFlags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildPluginServer).GenerateFlags(ctx, req.(*BuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuildPlugin_ServiceDesc is the grpc.ServiceDesc for BuildPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuildPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BuildPlugin",
	HandlerType: (*BuildPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _BuildPlugin_GetInfo_Handler,
		},
		{
			MethodName: "GenerateFlags",
			Handler:    _BuildPlugin_GenerateFlags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugin/proto/plugin.proto",
}

const (
	PatchPlugin_GetInfo_FullMethodName = "/proto.PatchPlugin/GetInfo"
	PatchPlugin_Patch_FullMethodName   = "/proto.PatchPlugin/Patch"
)

// PatchPluginClient is the client API for PatchPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PatchPlugin service - patches version in config/manifest files
type PatchPluginClient interface {
	GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PatchInfo, error)
	Patch(ctx context.Context, in *PatchRequest, opts ...grpc.CallOption) (*PatchResponse, error)
}

type patchPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPatchPluginClient(cc grpc.ClientConnInterface) PatchPluginClient {
	return &patchPluginClient{cc}
}

func (c *patchPluginClient) GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PatchInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchInfo)
	err := c.cc.Invoke(ctx, PatchPlugin_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patchPluginClient) Patch(ctx context.Context, in *PatchRequest, opts ...grpc.CallOption) (*PatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchResponse)
	err := c.cc.Invoke(ctx, PatchPlugin_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatchPluginServer is the server API for PatchPlugin service.
// All implementations must embed UnimplementedPatchPluginServer
// for forward compatibility.
//
// PatchPlugin service - patches version in config/manifest files
type PatchPluginServer interface {
	GetInfo(context.Context, *Empty) (*PatchInfo, error)
	Patch(context.Context, *PatchRequest) (*PatchResponse, error)
	mustEmbedUnimplementedPatchPluginServer()
}

// UnimplementedPatchPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPatchPluginServer struct{}

func (UnimplementedPatchPluginServer) GetInfo(context.Context, *Empty) (*PatchInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedPatchPluginServer) Patch(context.Context, *PatchRequest) (*PatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedPatchPluginServer) mustEmbedUnimplementedPatchPluginServer() {}
func (UnimplementedPatchPluginServer) testEmbeddedByValue()                     {}

// UnsafePatchPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PatchPluginServer will
// result in compilation errors.
type UnsafePatchPluginServer interface {
	mustEmbedUnimplementedPatchPluginServer()
}

func RegisterPatchPluginServer(s grpc.ServiceRegistrar, srv PatchPluginServer) {
	// If the following call panics, it indicates UnimplementedPatchPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PatchPlugin_ServiceDesc, srv)
}

func _PatchPlugin_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatchPluginServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatchPlugin_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatchPluginServer).GetInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatchPlugin_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatchPluginServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatchPlugin_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatchPluginServer).Patch(ctx, req.(*PatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PatchPlugin_ServiceDesc is the grpc.ServiceDesc for PatchPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PatchPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PatchPlugin",
	HandlerType: (*PatchPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _PatchPlugin_GetInfo_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _PatchPlugin_Patch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugin/proto/plugin.proto",
}
