// Package php provides the PHP/Composer language plugin for versionator.
//
// PHP projects using Composer have version in composer.json:
//
//	{
//	  "name": "vendor/package",
//	  "version": "1.2.3"
//	}
//
// The generated Version.php file contains:
//
//	<?php
//	// Auto-generated by versionator. Do not edit.
//
//	namespace Version;
//
//	class Version
//	{
//	    public const VERSION = '1.2.3';
//	    public const MAJOR = 1;
//	    public const MINOR = 2;
//	    public const PATCH = 3;
//	}
//
// Injection methods:
//   - emit: Generate Version.php with constants
//   - patch: Update version in composer.json
package php

import (
	"github.com/benjaminabbitt/versionator/internal/plugin"
)

// Plugin implements the LanguagePlugin interface for PHP/Composer
type Plugin struct{}

// Name returns the plugin name
func (p *Plugin) Name() string {
	return "php"
}

// Types returns the plugin types this plugin implements
func (p *Plugin) Types() plugin.PluginTypeSet {
	return plugin.NewPluginTypeSet(plugin.TypeLanguage)
}

// LanguageName returns the language identifier
func (p *Plugin) LanguageName() string {
	return "php"
}

// GetEmitConfig returns configuration for PHP source file emission
func (p *Plugin) GetEmitConfig() *plugin.EmitConfig {
	return &plugin.EmitConfig{
		DefaultOutputPath:  "src/Version.php",
		DefaultPackageName: "Version",
		FileExtension:      ".php",
	}
}

// GetBuildConfig returns nil - PHP doesn't support link-time injection
func (p *Plugin) GetBuildConfig() *plugin.LinkConfig {
	return nil
}

// GetPatchConfigs returns configuration for patching composer.json
func (p *Plugin) GetPatchConfigs() []plugin.PatchConfig {
	return []plugin.PatchConfig{
		{
			Name:        "composer.json",
			FilePath:    "composer.json",
			Format:      plugin.PatchFormatJSON,
			VersionPath: "version",
			Description: "Composer package manifest",
			Patch:       plugin.PatchJSON(),
		},
	}
}

func init() {
	plugin.Register(&Plugin{})
}
