// Package python provides the Python language plugin for versionator.
//
// Modern Python projects use pyproject.toml (PEP 621) for configuration:
//
//	[project]
//	name = "mypackage"
//	version = "1.2.3"
//
// The generated _version.py file contains:
//
//	"""Auto-generated by versionator. Do not edit."""
//
//	__version__ = "1.2.3"
//	__version_tuple__ = (1, 2, 3)
//	__git_hash__ = "abc1234"
//
// Import in your package's __init__.py:
//
//	from ._version import __version__
//
// For legacy setuptools projects (setup.cfg), use "python-setuptools" instead.
//
// Injection methods:
//   - emit: Generate _version.py with version variables
//   - patch: Update version in pyproject.toml
package python

import (
	"github.com/benjaminabbitt/versionator/pkg/plugin"
)

// Plugin implements the LanguagePlugin interface for Python
type Plugin struct{}

// Name returns the plugin name
func (p *Plugin) Name() string {
	return "python"
}

// Types returns the plugin types this plugin implements
func (p *Plugin) Types() plugin.PluginTypeSet {
	return plugin.NewPluginTypeSet(plugin.TypeLanguage)
}

// LanguageName returns the language identifier
func (p *Plugin) LanguageName() string {
	return "python"
}

// GetEmitConfig returns configuration for Python source file emission
func (p *Plugin) GetEmitConfig() *plugin.EmitConfig {
	return &plugin.EmitConfig{
		DefaultOutputPath:  "_version.py",
		DefaultPackageName: "",
		FileExtension:      ".py",
	}
}

// GetBuildConfig returns nil - Python doesn't support link-time injection
func (p *Plugin) GetBuildConfig() *plugin.LinkConfig {
	return nil
}

// GetPatchConfigs returns configuration for patching Python project files
func (p *Plugin) GetPatchConfigs() []plugin.PatchConfig {
	return []plugin.PatchConfig{
		{
			Name:        "pyproject.toml",
			FilePath:    "pyproject.toml",
			Format:      plugin.PatchFormatTOML,
			VersionPath: "project.version",
			Description: "Python project manifest (PEP 621)",
			Patch:       plugin.PatchTOML(),
		},
		{
			Name:        "setup.py",
			FilePath:    "setup.py",
			Format:      plugin.PatchFormatPython,
			VersionPath: "version",
			Description: "Python setup script (legacy)",
			Patch:       plugin.PatchPythonSetup(),
		},
	}
}

func init() {
	plugin.Register(&Plugin{})
}
