// Package swift provides the Swift language plugin for versionator.
//
// Swift packages use Package.swift as the manifest file. Since Package.swift
// doesn't have a standard version field, we use a comment-based convention:
//
//	// VERSION: 1.2.3
//
// The generated Version.swift file contains:
//
//	// Auto-generated by versionator. Do not edit.
//
//	public let VERSION = "1.2.3"
//	public let MAJOR = 1
//	public let MINOR = 2
//	public let PATCH = 3
//
// Injection methods:
//   - emit: Generate Version.swift with version constants
//   - patch: Update // VERSION: comment in Package.swift
package swift

import (
	"github.com/benjaminabbitt/versionator/pkg/plugin"
)

// Plugin implements the LanguagePlugin interface for Swift
type Plugin struct{}

// Name returns the plugin name
func (p *Plugin) Name() string {
	return "swift"
}

// Types returns the plugin types this plugin implements
func (p *Plugin) Types() plugin.PluginTypeSet {
	return plugin.NewPluginTypeSet(plugin.TypeLanguage)
}

// LanguageName returns the language identifier
func (p *Plugin) LanguageName() string {
	return "swift"
}

// GetEmitConfig returns configuration for Swift source file emission
func (p *Plugin) GetEmitConfig() *plugin.EmitConfig {
	return &plugin.EmitConfig{
		DefaultOutputPath:  "Sources/Version.swift",
		DefaultPackageName: "",
		FileExtension:      ".swift",
	}
}

// GetBuildConfig returns nil - Swift doesn't support link-time injection
func (p *Plugin) GetBuildConfig() *plugin.LinkConfig {
	return nil
}

// GetPatchConfigs returns configuration for patching Package.swift
func (p *Plugin) GetPatchConfigs() []plugin.PatchConfig {
	return []plugin.PatchConfig{
		{
			Name:        "Package.swift",
			FilePath:    "Package.swift",
			Format:      plugin.PatchFormatSwift,
			VersionPath: "version",
			Description: "Swift Package Manager manifest (comment-based)",
			Patch:       plugin.PatchSwiftPackage(),
		},
	}
}

func init() {
	plugin.Register(&Plugin{})
}
