name: Build and Test

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and run dev container action
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/${{ github.repository }}/devcontainer
        cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
        push: filter
        refFilterForPush: refs/heads/master
        runCmd: |
          # Run initialization
          just init

          # Run tests
          # just test-coverage

          # Run lining
          # just lint

          # Build for multiple platforms
          just build-all

          # Test basic functionality
          just version || echo "No VERSION file - expected for new repo"

          # Show build artifacts
          ls -la bin/
        dockerOptions: |
          --volume ${{ github.workspace }}/bin:/workspace/bin

    - name: Upload coverage reports
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.html
        retention-days: 30

    - name: Upload Linux amd64 binary
      uses: actions/upload-artifact@v4
      with:
        name: versionator-linux-amd64
        path: bin/versionator-linux-amd64
        retention-days: 30

    - name: Upload Linux arm64 binary
      uses: actions/upload-artifact@v4
      with:
        name: versionator-linux-arm64
        path: bin/versionator-linux-arm64
        retention-days: 30

    - name: Upload macOS amd64 binary
      uses: actions/upload-artifact@v4
      with:
        name: versionator-darwin-amd64
        path: bin/versionator-darwin-amd64
        retention-days: 30

    - name: Upload macOS arm64 binary
      uses: actions/upload-artifact@v4
      with:
        name: versionator-darwin-arm64
        path: bin/versionator-darwin-arm64
        retention-days: 30

    - name: Upload Windows amd64 binary
      uses: actions/upload-artifact@v4
      with:
        name: versionator-windows-amd64.exe
        path: bin/versionator-windows-amd64.exe
        retention-days: 30

    - name: Upload Windows arm64 binary
      uses: actions/upload-artifact@v4
      with:
        name: versionator-windows-arm64.exe
        path: bin/versionator-windows-arm64.exe
        retention-days: 30

    - name: Upload FreeBSD amd64 binary
      uses: actions/upload-artifact@v4
      with:
        name: versionator-freebsd-amd64
        path: bin/versionator-freebsd-amd64
        retention-days: 30
#
#  integration-test:
#    runs-on: ubuntu-latest
#    needs: build-and-test
#    env:
#      LINUX_BINARY: versionator-linux-amd64
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v4
#
#    - name: Download build artifacts
#      uses: actions/download-artifact@v4
#      with:
#        name: application-binaries
#        path: bin/
#
#    - name: Make binary executable
#      run: chmod +x bin/${{ env.LINUX_BINARY }}
#
#    - name: Setup integration test environment
#      run: |
#        # Create a temporary directory outside the repository
#        TEMP_TEST_DIR=$(mktemp -d)
#        echo "TEMP_TEST_DIR=$TEMP_TEST_DIR" >> $GITHUB_ENV
#
#        # Copy the integration test script to temp directory
#        cp integration_test/run_integration_test.sh $TEMP_TEST_DIR/
#        chmod +x $TEMP_TEST_DIR/run_integration_test.sh
#
#        # Copy the binary to temp directory for easier access
#        cp bin/${{ env.LINUX_BINARY }} $TEMP_TEST_DIR/
#
#        echo "Integration test environment created at: $TEMP_TEST_DIR"
#
#    - name: Run integration test from outside repository
#      run: |
#        # Change to temp directory (outside repository)
#        cd ${{ env.TEMP_TEST_DIR }}
#
#        # Run the integration test script
#        ./run_integration_test.sh ./${{ env.LINUX_BINARY }}

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [build-and-test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Linux amd64 binary
      uses: actions/download-artifact@v4
      with:
        name: versionator-linux-amd64
        path: release/

    - name: Download Linux arm64 binary
      uses: actions/download-artifact@v4
      with:
        name: versionator-linux-arm64
        path: release/

    - name: Download macOS amd64 binary
      uses: actions/download-artifact@v4
      with:
        name: versionator-darwin-amd64
        path: release/

    - name: Download macOS arm64 binary
      uses: actions/download-artifact@v4
      with:
        name: versionator-darwin-arm64
        path: release/

    - name: Download Windows amd64 binary
      uses: actions/download-artifact@v4
      with:
        name: versionator-windows-amd64.exe
        path: release/

    - name: Download Windows arm64 binary
      uses: actions/download-artifact@v4
      with:
        name: versionator-windows-arm64.exe
        path: release/

    - name: Download FreeBSD amd64 binary
      uses: actions/download-artifact@v4
      with:
        name: versionator-freebsd-amd64
        path: release/

    - name: Create checksums
      run: |
        # Create checksums for all downloaded binaries
        cd release
        sha256sum * > checksums.txt
        ls -la

    - name: Upload checksums
      uses: actions/upload-artifact@v4
      with:
        name: checksums.txt
        path: release/checksums.txt
        retention-days: 90