package app;

/**
 * Auto-generated by versionator {{VersionatorVersion}}. Do not edit.
 * Utility holder for the build-time version string. This class should never be instantiated.
 */
public final class BuildTime {
    /**
     * Build-time version string injected by the build.
     */
    public static final String VERSION = "{{Version}}";

    /**
     * Private constructor to prevent instantiation.
     */
    private BuildTime() {
        // This class should not be instantiated.
    }
}
